Repository RAF-SI-2022/Bolnica-2-Frontend, pull requests merged in 2023-06, with the labels that each got.

#117 postsubmits task now downloads helm chart
  .prow/postsubmits.yaml
Labels: size/XS

#118 issue 92: patient condition history and register
  src/app/app-routing.module.ts
  src/app/app.constants.ts
  src/app/app.module.ts
  src/app/components/patients/patient-condition-history/patient-condition-history.component.css
  src/app/components/patients/patient-condition-history/patient-condition-history.component.html
  src/app/components/patients/patient-condition-history/patient-condition-history.component.spec.ts
  src/app/components/patients/patient-condition-history/patient-condition-history.component.ts
  src/app/components/patients/register-patient-condition/register-patient-condition.component.css
  src/app/components/patients/register-patient-condition/register-patient-condition.component.html
  src/app/components/patients/register-patient-condition/register-patient-condition.component.spec.ts
  src/app/components/patients/register-patient-condition/register-patient-condition.component.ts
  src/app/dto/request/patient.request.ts
  src/app/dto/response/condition-history.response.ts
  src/app/service/patient.service.ts
Labels: size/L

#121 Upadte za issues 95 i 92
  src/app/app-routing.module.ts
  src/app/app.module.ts
  src/app/components/doctor-search-stationary-patients/doctor-search-stationary-patients.component.css
  src/app/components/doctor-search-stationary-patients/doctor-search-stationary-patients.component.html
  src/app/components/doctor-search-stationary-patients/doctor-search-stationary-patients.component.spec.ts
  src/app/components/doctor-search-stationary-patients/doctor-search-stationary-patients.component.ts
  src/app/components/doctor-stationary-menu/doctor-stationary-menu.component.css
  src/app/components/doctor-stationary-menu/doctor-stationary-menu.component.html
  src/app/components/doctor-stationary-menu/doctor-stationary-menu.component.spec.ts
  src/app/components/doctor-stationary-menu/doctor-stationary-menu.component.ts
  src/app/components/home/home.component.html
  src/app/components/nurse-stationary-menu/nurse-stationary-menu.component.css
  src/app/components/nurse-stationary-menu/nurse-stationary-menu.component.html
  src/app/components/nurse-stationary-menu/nurse-stationary-menu.component.spec.ts
  src/app/components/nurse-stationary-menu/nurse-stationary-menu.component.ts
  src/app/components/search-stationary-patients/search-stationary-patients.component.css
  src/app/components/search-stationary-patients/search-stationary-patients.component.html
  src/app/components/search-stationary-patients/search-stationary-patients.component.spec.ts
  src/app/components/search-stationary-patients/search-stationary-patients.component.ts
  src/app/components/stationary/nurse/menu/stationary-menu.component.html
  src/app/components/stationary/nurse/view-appointments/view-appointments.component.ts
  src/app/service/patient.service.ts
  src/assets/images/card-list.svg
  src/assets/images/clipboard-plus.svg
  src/assets/images/clock-history.svg
  src/assets/images/file-earmark-medical.svg
Labels: size/XL

#120 Sprint4
  src/app/app-routing.module.ts
  src/app/app.constants.ts
  src/app/app.module.ts
  src/app/components/patients/health-records/health-record/health-record.component.html
  src/app/components/patients/patient-condition-history/patient-condition-history.component.css
  src/app/components/patients/patient-condition-history/patient-condition-history.component.html
  src/app/components/patients/patient-condition-history/patient-condition-history.component.spec.ts
  src/app/components/patients/patient-condition-history/patient-condition-history.component.ts
  src/app/components/patients/register-patient-condition/register-patient-condition.component.css
  src/app/components/patients/register-patient-condition/register-patient-condition.component.html
  src/app/components/patients/register-patient-condition/register-patient-condition.component.spec.ts
  src/app/components/patients/register-patient-condition/register-patient-condition.component.ts
  src/app/components/referrals/referral-history/referral-history.component.html
  src/app/components/stationary/doc-patient-condition-history/doc-patient-condition-history.component.css
  src/app/components/stationary/doc-patient-condition-history/doc-patient-condition-history.component.html
  src/app/components/stationary/doc-patient-condition-history/doc-patient-condition-history.component.spec.ts
  src/app/components/stationary/doc-patient-condition-history/doc-patient-condition-history.component.ts
  src/app/components/stationary/doc-stationary-discharge-history/doc-stationary-discharge-history.component.css
  src/app/components/stationary/doc-stationary-discharge-history/doc-stationary-discharge-history.component.html
  src/app/components/stationary/doc-stationary-discharge-history/doc-stationary-discharge-history.component.spec.ts
  src/app/components/stationary/doc-stationary-discharge-history/doc-stationary-discharge-history.component.ts
  src/app/components/stationary/doc-stationary-medical-report-history/doc-stationary-medical-report-history.component.css
  src/app/components/stationary/doc-stationary-medical-report-history/doc-stationary-medical-report-history.component.html
  src/app/components/stationary/doc-stationary-medical-report-history/doc-stationary-medical-report-history.component.spec.ts
  src/app/components/stationary/doc-stationary-medical-report-history/doc-stationary-medical-report-history.component.ts
  src/app/components/stationary/doctor/discharge-list/discharge-list.component.css
  src/app/components/stationary/doctor/discharge-list/discharge-list.component.html
  src/app/components/stationary/doctor/discharge-list/discharge-list.component.spec.ts
  src/app/components/stationary/doctor/discharge-list/discharge-list.component.ts
  src/app/components/stationary/doctor/health-report/health-report.component.css
  src/app/components/stationary/doctor/health-report/health-report.component.html
  src/app/components/stationary/doctor/health-report/health-report.component.spec.ts
  src/app/components/stationary/doctor/health-report/health-report.component.ts
  src/app/dto/request/patient.request.ts
  src/app/dto/response/condition-history.response.ts
  src/app/service/patient.service.ts
Labels: size/XXL

#130 reception-visits
  src/app/app-routing.module.ts
  src/app/app.module.ts
  src/app/components/home/home.component.html
  src/app/components/reception/visits/reception-visits.component.css
  src/app/components/reception/visits/reception-visits.component.html
  src/app/components/reception/visits/reception-visits.component.spec.ts
  src/app/components/reception/visits/reception-visits.component.ts
Labels: size/L

#134 add kubernetes config changes for backend
  kubernetes/bolnica-2/templates/ingress.yaml
  kubernetes/bolnica-2/templates/statistics-service.yaml
Labels: size/M

#135 .
  src/app/app.constants.ts
  src/app/components/covid/covid-stats/covid-stats.component.ts
  src/app/components/stationary/doctor/discharge-list/discharge-list.component.ts
  src/app/components/stationary/nurse/visit-history/visit-history.component.html
  src/app/service/stats.service.ts
Labels: size/S

#137 revert changes
  .prow/postsubmits.yaml
Labels: size/XS

#159 Sprint6
  src/app/app-routing.module.ts
  src/app/app.module.ts
  src/app/components/covid/covid/covid.component.html
  src/app/components/laboratory/lab-visits/search-scheduled-lab-visits/search-scheduled-lab-visits.component.ts
  src/app/covid/patients-for-covid-exam-list/patients-for-covid-exam-list.component.css
  src/app/covid/patients-for-covid-exam-list/patients-for-covid-exam-list.component.html
  src/app/covid/patients-for-covid-exam-list/patients-for-covid-exam-list.component.spec.ts
  src/app/covid/patients-for-covid-exam-list/patients-for-covid-exam-list.component.ts
  src/app/service/patient.service.ts
Labels: size/L
