Repository RAF-SI-2022/Bolnica-2-Frontend, pull requests merged in 2023-04, with the labels that each got.

#51 pregled doktora dodat
  package-lock.json
  package.json
  src/app/app-routing.module.ts
  src/app/app.module.ts
  src/app/components/search-patients/search-patients.component.html
  src/app/components/specialist-doctor-examination/specialist-doctor-examination.component.css
  src/app/components/specialist-doctor-examination/specialist-doctor-examination.component.html
  src/app/components/specialist-doctor-examination/specialist-doctor-examination.component.spec.ts
  src/app/components/specialist-doctor-examination/specialist-doctor-examination.component.ts
  src/app/dto/request/patient.request.ts
  src/app/dto/response/health-record.response.ts
  src/app/service/health-record.service.ts
Labels: size/XL

#45 Sprint 2 - Scheduled appointments za lekare i medicinske sestre - init commit
  src/app/app-routing.module.ts
  src/app/app.module.ts
  src/app/components/scheduled-appointments/scheduled-appointments.component.css
  src/app/components/scheduled-appointments/scheduled-appointments.component.html
  src/app/components/scheduled-appointments/scheduled-appointments.component.spec.ts
  src/app/components/scheduled-appointments/scheduled-appointments.component.ts
  src/app/dto/response/scheduled-appointment-response.ts
  src/app/service/scheduled-appointment.service.ts
Labels: size/L

#53 Sprint 2
  src/app/app-routing.module.ts
  src/app/app.module.ts
  src/app/components/health-records/basic-health-record/basic-health-record.component.css
  src/app/components/health-records/basic-health-record/basic-health-record.component.html
  src/app/components/health-records/basic-health-record/basic-health-record.component.spec.ts
  src/app/components/health-records/basic-health-record/basic-health-record.component.ts
  src/app/components/health-records/full-medical-history/full-medical-history.component.css
  src/app/components/health-records/full-medical-history/full-medical-history.component.html
  src/app/components/health-records/full-medical-history/full-medical-history.component.spec.ts
  src/app/components/health-records/full-medical-history/full-medical-history.component.ts
  src/app/components/health-records/health-record/health-record.component.css
  src/app/components/health-records/health-record/health-record.component.html
  src/app/components/health-records/health-record/health-record.component.spec.ts
  src/app/components/health-records/health-record/health-record.component.ts
  src/app/components/health-records/illness-history-record/illness-history-record.component.css
  src/app/components/health-records/illness-history-record/illness-history-record.component.html
  src/app/components/health-records/illness-history-record/illness-history-record.component.spec.ts
  src/app/components/health-records/illness-history-record/illness-history-record.component.ts
  src/app/components/health-records/medical-history-record/medical-history-record.component.css
  src/app/components/health-records/medical-history-record/medical-history-record.component.html
  src/app/components/health-records/medical-history-record/medical-history-record.component.spec.ts
  src/app/components/health-records/medical-history-record/medical-history-record.component.ts
  src/app/components/search-patients/search-patients.component.html
  src/app/components/search-patients/search-patients.component.ts
  src/app/dto/request/health-record.request.ts
  src/app/dto/response/health-record.response.ts
  src/app/service/health-record.service.ts
  src/app/service/patient.service.ts
Labels: size/XXL

#57 poboljsane funkcionalnosti
  src/app/components/specialist-doctor-examination/specialist-doctor-examination.component.html
  src/app/components/specialist-doctor-examination/specialist-doctor-examination.component.ts
Labels: size/S

#55 Sprint 2
  src/app/app-routing.module.ts
  src/app/app.module.ts
  src/app/components/edit-patient/edit-patient.component.css
  src/app/components/edit-patient/edit-patient.component.html
  src/app/components/edit-patient/edit-patient.component.spec.ts
  src/app/components/edit-patient/edit-patient.component.ts
  src/app/components/new-patient/new-patient.component.html
  src/app/dto/response/patient.response.ts
  src/app/service/patient.service.ts
Labels: size/XL

#75 Sprint3
  src/app/app-routing.module.ts
  src/app/app.component.html
  src/app/app.constants.ts
  src/app/app.module.ts
  src/app/components/edit-patient/edit-patient.component.ts
  src/app/components/home/home.component.html
  src/app/components/new-work-order/new-work-order.component.css
  src/app/components/new-work-order/new-work-order.component.html
  src/app/components/new-work-order/new-work-order.component.spec.ts
  src/app/components/new-work-order/new-work-order.component.ts
  src/app/components/scheduled-patients/scheduled-patients.component.css
  src/app/components/scheduled-patients/scheduled-patients.component.html
  src/app/components/scheduled-patients/scheduled-patients.component.spec.ts
  src/app/components/scheduled-patients/scheduled-patients.component.ts
  src/app/dto/response/appointed.patient.ts
  src/app/dto/response/unprocessed.refferal.ts
  src/app/service/health-record.service.ts
  src/app/service/scheduled-appointment.service.ts
  src/assets/images/bi-file-text.svg
  src/assets/images/bi-layout-text-sidebar-reverse.svg
Labels: size/XL

#76 Sprint 3 - Biochem component and bug fixes for scheduled component
  src/app/app-routing.module.ts
  src/app/app.constants.ts
  src/app/app.module.ts
  src/app/components/home/home.component.html
  src/app/components/search-biochem-acc/search-biochem-acc.component.css
  src/app/components/search-biochem-acc/search-biochem-acc.component.html
  src/app/components/search-biochem-acc/search-biochem-acc.component.spec.ts
  src/app/components/search-biochem-acc/search-biochem-acc.component.ts
  src/app/dto/response/search-biochem-response.ts
  src/app/service/scheduled-appointment.service.ts
  src/app/service/search-biochem.service.ts
  src/assets/images/eyedropper.svg
Labels: size/L

#77 Lab
  src/app/app-routing.module.ts
  src/app/app.module.ts
  src/app/components/full-issuing-results/full-issuing-results.component.css
  src/app/components/full-issuing-results/full-issuing-results.component.html
  src/app/components/full-issuing-results/full-issuing-results.component.spec.ts
  src/app/components/full-issuing-results/full-issuing-results.component.ts
  src/app/components/home/home.component.html
  src/app/components/issuing-results/issuing-results.component.css
  src/app/components/issuing-results/issuing-results.component.html
  src/app/components/issuing-results/issuing-results.component.spec.ts
  src/app/components/issuing-results/issuing-results.component.ts
  src/app/dto/request/issued-results.request.ts
  src/app/service/issue-results.service.ts
  src/app/service/lab.service.ts
Labels: size/XL

#80 recepcioner
  src/app/components/home/home.component.html
  src/app/components/issuing-results/issuing-results.component.html
  src/app/components/issuing-results/issuing-results.component.ts
  src/app/components/new-appointment/new-appointment.component.html
  src/app/components/new-appointment/new-appointment.component.ts
  src/app/service/auth.service.ts
  src/app/service/employee.service.ts
  src/app/service/lab.service.ts
Labels: size/L

#81 kt3 - biochem component
  src/app/components/search-biochem-acc/search-biochem-acc.component.html
  src/app/components/search-biochem-acc/search-biochem-acc.component.ts
  src/app/dto/request/search-biochem-request.ts
  src/app/dto/response/search-biochem-response.ts
  src/app/service/search-biochem.service.ts
Labels: size/L

#87 Sprint 3
  src/app/service/scheduled-appointment.service.ts
Labels: size/XS

#72 Devops update
  Dockerfile
  angular.json
  docker-compose.yaml
  package.json
Labels: size/M
