Repository RAF-SI-2022/Bolnica-2-Frontend, pull requests merged in 2023-03, with the labels that each got.

#1 Generate angular project
  .browserslistrc
  .editorconfig
  .gitignore
  .vscode/extensions.json
  .vscode/launch.json
  .vscode/tasks.json
  README.md
  angular.json
  karma.conf.js
  package-lock.json
  package.json
  src/app/app-routing.module.ts
  src/app/app.component.css
  src/app/app.component.html
  src/app/app.component.spec.ts
  src/app/app.component.ts
  src/app/app.module.ts
  src/assets/.gitkeep
  src/environments/environment.prod.ts
  src/environments/environment.ts
  src/favicon.ico
  src/index.html
  src/main.ts
  src/polyfills.ts
  src/styles.css
  src/test.ts
  tsconfig.app.json
  tsconfig.json
  tsconfig.spec.json
Labels: size/XXL, needs-ok-to-test

#4 test commit
  README.md
Labels: size/XS

#3 login i forgot password komponente
  src/app/app-routing.module.ts
  src/app/app.component.html
  src/app/app.component.ts
  src/app/app.constants.ts
  src/app/app.module.ts
  src/app/auth.service.ts
  src/app/forgot-password/forgot-password.component.css
  src/app/forgot-password/forgot-password.component.html
  src/app/forgot-password/forgot-password.component.spec.ts
  src/app/forgot-password/forgot-password.component.ts
  src/app/guard/auth.guard.ts
  src/app/login/login.component.css
  src/app/login/login.component.html
  src/app/login/login.component.spec.ts
  src/app/login/login.component.ts
  src/assets/images/logo.svg
  src/index.html
  src/styles.css
Labels: size/L, kind/frontend

#7 home page template
  src/app/app-routing.module.ts
  src/app/app.component.html
  src/app/app.component.ts
  src/app/app.module.ts
  src/app/home/home.component.css
  src/app/home/home.component.html
  src/app/home/home.component.spec.ts
  src/app/home/home.component.ts
  src/assets/images/hospital.png
  src/assets/images/person-circle.svg
  src/assets/images/search.svg
  src/index.html
  src/styles.css
Labels: kind/frontend, sprint 1

#12 New employee page
  src/app/app-routing.module.ts
  src/app/app.module.ts
  src/app/home/home.component.html
  src/app/new-employee/new-employee.component.css
  src/app/new-employee/new-employee.component.html
  src/app/new-employee/new-employee.component.spec.ts
  src/app/new-employee/new-employee.component.ts
  src/assets/images/person-plus-fill.svg
Labels: lgtm, approved, size/XL

#18 Reorganizing layout
  src/app/new-employee/new-employee.component.html
Labels: size/L

#20 Sprint 1
  .gitignore
  package-lock.json
  package.json
  src/app/app-routing.module.ts
  src/app/app.component.css
  src/app/app.component.html
  src/app/app.module.ts
  src/app/dto/request/update.employee.request.ts
  src/app/dto/response/employee.response.ts
  src/app/dto/response/profession.response.ts
  src/app/dto/response/title.response.ts
  src/app/home/home.component.html
  src/app/home/home.component.ts
  src/app/personal-data/personal-data.component.css
  src/app/personal-data/personal-data.component.html
  src/app/personal-data/personal-data.component.spec.ts
  src/app/personal-data/personal-data.component.ts
  src/app/service/auth.service.ts
  src/app/service/employee.service.ts
Labels: size/L

#22 reogranized layout
  src/app/admin-edit-employee/admin-edit-employee.component.ts
  src/app/app-routing.module.ts
  src/app/app.component.html
  src/app/app.module.ts
  src/app/dto/request/update.employee.request.ts
  src/app/dto/response/employee.response.ts
  src/app/dto/response/profession.response.ts
  src/app/dto/response/title.response.ts
  src/app/guard/already-logged-in.guard.ts
  src/app/guard/permission.guard.ts
  src/app/home/home.component.html
  src/app/home/home.component.ts
  src/app/login/login.component.html
  src/app/login/login.component.ts
  src/app/new-employee/new-employee.component.html
  src/app/personal-data/personal-data.component.html
  src/app/personal-data/personal-data.component.ts
  src/app/pipe/boolean.pipe.ts
  src/app/search-employees/search-employees.component.ts
  src/app/service/auth.service.ts
  src/assets/images/box-arrow-in-right.svg
  src/styles.css
Labels: size/XXL

#39 template za zakazivanje novog pregleda
  package-lock.json
  package.json
  src/app/app-routing.module.ts
  src/app/app.component.html
  src/app/app.module.ts
  src/app/components/home/home.component.html
  src/app/components/new-appointment/new-appointment.component.css
  src/app/components/new-appointment/new-appointment.component.html
  src/app/components/new-appointment/new-appointment.component.spec.ts
  src/app/components/new-appointment/new-appointment.component.ts
  src/styles.css
Labels: size/L

#41 DTO patients/healthRecord/SchedMedExam
  src/app/app-routing.module.ts
  src/app/app.component.html
  src/app/app.constants.ts
  src/app/app.module.ts
  src/app/components/home/home.component.html
  src/app/components/search-employees/search-employees.component.ts
  src/app/components/search-patients/search-patients.component.css
  src/app/components/search-patients/search-patients.component.html
  src/app/components/search-patients/search-patients.component.spec.ts
  src/app/components/search-patients/search-patients.component.ts
  src/app/dto/request/patient.request.ts
  src/app/dto/request/sched-med-exam.request.ts
  src/app/dto/response/health-record.response.ts
  src/app/dto/response/patient.response.ts
  src/app/dto/response/sched-med-exam.response.ts
  src/app/service/health-record.service.ts
  src/app/service/patient.service.ts
  src/app/service/sched-med-exam.service.ts
Labels: size/XL
